apiVersion: v1
kind: ServiceAccount
metadata:
  name: client
---
apiVersion: v1
kind: Pod
metadata:
  name: client
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  terminationGracePeriodSeconds: 0
  serviceAccountName: client
  containers:
  - name: sleep
    image: curlimages/curl
    command: ["/bin/sleep", "3650d"]
  - name: uproxy
    image: envoyproxy/envoy:v1.19.1
    command: ["envoy", "--config-path", "/workspace/config.yaml", "--concurrency", "2"]
    volumeMounts:
    - mountPath: /workspace
      name: envoy-config
      readOnly: true
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsGroup: 1337
      runAsNonRoot: true
      runAsUser: 1337
  initContainers:
  - args:
    - istio-iptables
    - -p
    - "15001"
    - -z
    - "15006"
    - -u
    - "1337"
    - -m
    - REDIRECT
    - -i
    - '*'
    - -x
    - ""
    - -b
    - '*'
    - -d
    - 15090,15021,15020
    image: docker.io/istio/proxyv2:1.11.1
    name: istio-init
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 128Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: false
      runAsGroup: 0
      runAsNonRoot: false
      runAsUser: 0
  volumes:
  - name: envoy-config
    configMap:
      name: client-uproxy
